### ISSUE TITLE
NameError: name 'trait_index' is not defined

### ISSUE THREAD

**Issue by ushadi97** [desaichirayu/Personality-Attribution-using-Natural-Language-Processing#1]
@desaichirayu ,

Can you please addressed the issue which is mentioned below. Here it says, trait_index is not defined.

line 101, in <module>     
    trait, default_alpha = get_choice(trait_index)
NameError: name 'trait_index' is not defined

Thanks

**Comment by desaichirayu** [comment]
@ushadi97 This is not an issue. trait_index is a local variable that takes values from your command line argument. Please refer to the example usage below:

Example usage: 
```
$python mlp_kfold.py <trait>
```

> <trait> can take vales form 0 to 4 based on the trait for which the user wants to run model denoted by:
> 0: Extraversion
> 1: Neuroticism
> 2: Agreeableness
> 3: Conscientiousness
> 4: Openness

**Comment by ushadi97** [comment]
@desaichirayu thank you very much.
